name: Deploy to AWS S3

on:
    push:

jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            AWS_S3_BUCKET: it342-spiderweb
            AWS_REGION: us-east-2
            SOURCE_DIR: ./

        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: aws credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ env.AWS_REGION }}

            - name: upload to s3
              run: |
                  aws s3 sync ${{ env.SOURCE_DIR }} s3://${{ env.AWS_S3_BUCKET }} --delete
