name: Build and Deploy to EC2

on:
    push:
        branches:
            - main

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: setup node
              uses: actions/setup-node@v4
              with:
                  node-version: "18"
                  cache: "npm"

            - name: npm run build
              run: |
                  npm ci
                  npm run build

            - name: deploy directories
              uses: easingthemes/ssh-deploy@v5.0.0
              with:
                  SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
                  REMOTE_HOST: ${{ secrets.EC2_HOST }}
                  REMOTE_USER: ${{ secrets.EC2_USER }}
                  SOURCE: ".next/ public/"
                  TARGET: "/var/www/spiderweb"
                  ARGS: "--delete"

            - name: config files
              uses: easingthemes/ssh-deploy@v5.0.0
              with:
                  SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
                  REMOTE_HOST: ${{ secrets.EC2_HOST }}
                  REMOTE_USER: ${{ secrets.EC2_USER }}
                  SOURCE: "package.json package-lock.json next.config.js"
                  TARGET: "/var/www/spiderweb"

            - name: restart pm2
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USER }}
                  key: ${{ secrets.EC2_SSH_KEY }}
                  script: |
                      cd /var/www/spiderweb
                      npm ci --production
                      pm2 describe spiderweb > /dev/null
                      if [ $? -eq 0 ]; then
                          echo "spiderweb already exists"
                          pm2 restart spiderweb
                      else
                          echo "starting on port 3000"
                          pm2 start npm --name "spiderweb" -- start -p 3000
                      fi
                      pm2 save
