name: Build and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: npm
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: npm ci
        run: npm ci

      - name: npm run build
        run: npm run build

      - name: deploy directories
        uses: easingthemes/ssh-deploy@v5.0.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: ${{ secrets.EC2_USER }}
          SOURCE: ".next public/"
          TARGET: "/var/www/spiderweb"
          ARGS: "--delete"

      - name: config files
        uses: easingthemes/ssh-deploy@v5.0.0
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: ${{ secrets.EC2_USER }}
          SOURCE: "package.json package-lock.json next.config.js ecosystem.config.js"
          TARGET: "/var/www/spiderweb"

      - name: Install Prod Dependencies, Create .env, and Reload App
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          timeout: 2400s
          script: |
            cd /var/www/spiderweb

            echo "Creating prod.env file..."
            cat << EOF > prod.env
            NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }}
            NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }}

            PG_HOST=${{ secrets.PG_HOST }}
            PG_USER=${{ secrets.PG_USER }}
            PG_PASSWORD=${{ secrets.PG_PASSWORD }}
            PG_DATABASE=postgres
            PG_PORT=5432
            EOF
            echo "prod.env created successfully."

            npm ci --omit=dev

            pm2 startOrRestart ecosystem.config.js --update-env
                      
            pm2 save
